Document: svnbackup
Title: Debian svnbackup Manual
Author: <insert document author here>
Abstract: This manual describes what svnbackup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/svnbackup/svnbackup.sgml.gz

Format: postscript
Files: /usr/share/doc/svnbackup/svnbackup.ps.gz

Format: text
Files: /usr/share/doc/svnbackup/svnbackup.text.gz

Format: HTML
Index: /usr/share/doc/svnbackup/html/index.html
Files: /usr/share/doc/svnbackup/html/*.html


